// @ts-nocheck
import mongoose from 'mongoose';
import { env } from './config/env.js';
import Mission from './modules/missions/mission.model.js';

interface MissionInput {
  title: string;
  slug: string;
  category: 'health' | 'housing' | 'shopping' | 'work' | 'social' | 'technology' | 'education' | 'government' | 'finance' | 'citizenship';
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1';
  order: number;
  description: string;
  scenarioPrompt: string;
  npcName: string;
  npcRole: string;
  requiredPhrases: string[];
  language?: "da";
}

const missions = [
  //╔══════════════════════════════════════════════════════════════╗
  //║  A1 — 10 missions (Beginner)                               ║
  //╚══════════════════════════════════════════════════════════════╝
  { title: 'Spørg i Netto', slug: 'ask-in-netto', category: 'shopping', level: 'A1', order: 1,
    description: 'Ask a shop assistant where to find something in the supermarket.',
    scenarioPrompt: 'You are shopping in Netto and cannot find the milk. Ask a shop assistant for help.',
    npcName: 'Lone', npcRole: 'Netto-medarbejder (Netto employee)',
    requiredPhrases: ['Undskyld', 'Hvor finder jeg mælk?', 'Tak for hjælpen'] },
  { title: 'Købe en bøtte smør', slug: 'buy-butter', category: 'shopping', level: 'A1', order: 2,
    description: 'Buy butter at the supermarket and pay at the register.',
    scenarioPrompt: 'You are at the checkout in Føtex. You need to buy butter and pay.',
    npcName: 'Klara', npcRole: 'kasseassistent (checkout assistant)',
    requiredPhrases: ['Hej', 'Jeg vil gerne betale', 'Tak'] },
  { title: 'Bestille en kop kaffe', slug: 'order-coffee', category: 'shopping', level: 'A1', order: 3,
    description: 'Order a coffee at a café.',
    scenarioPrompt: 'You are at a café in Copenhagen. Order a coffee and a pastry.',
    npcName: 'Mikkel', npcRole: 'café-medarbejder (café worker)',
    requiredPhrases: ['Jeg vil gerne have en kaffe', 'Hvor meget koster det?', 'Tak'] },
  { title: 'Sige hej og farvel', slug: 'say-hello-goodbye', category: 'social', level: 'A1', order: 4,
    description: 'Greet someone and introduce yourself in Danish.',
    scenarioPrompt: 'You meet a new neighbour in the apartment building. Say hello and introduce yourself.',
    npcName: 'Emma', npcRole: 'ny nabo (new neighbour)',
    requiredPhrases: ['Hej, jeg hedder', 'Hyggeligt at møde dig', 'Farvel'] },
  { title: 'Spørge om vej', slug: 'ask-for-directions', category: 'social', level: 'A1', order: 5,
    description: 'Ask for directions to the train station.',
    scenarioPrompt: 'You are lost in the city centre. Ask a stranger for directions to the nearest train station.',
    npcName: 'Oliver', npcRole: 'forbipasserende (passerby)',
    requiredPhrases: ['Undskyld, hvor er stationen?', 'Til højre', 'Mange tak'] },
  { title: 'Købe en billett', slug: 'buy-ticket', category: 'shopping', level: 'A1', order: 6,
    description: 'Buy a train ticket at the station.',
    scenarioPrompt: 'You need to buy a single ticket from Copenhagen to Roskilde at the ticket counter.',
    npcName: 'Signe', npcRole: 'billetsælger (ticket seller)',
    requiredPhrases: ['En billet til Roskilde', 'Hvad koster det?', 'Tak for hjælpen'] },
  { title: 'Bestille pizza', slug: 'order-pizza', category: 'shopping', level: 'A1', order: 7,
    description: 'Order a pizza over the phone.',
    scenarioPrompt: 'You call a pizzeria to order a pizza for delivery.',
    npcName: 'Hassan', npcRole: 'pizzamand (pizza maker)',
    requiredPhrases: ['Jeg vil gerne bestille en pizza', 'Hvad koster det?', 'Tak'] },
  { title: 'På biblioteket', slug: 'at-library', category: 'education', level: 'A1', order: 8,
    description: 'Ask about getting a library card.',
    scenarioPrompt: 'You are at the public library. Ask how to get a library card.',
    npcName: 'Ida', npcRole: 'bibliotekar (librarian)',
    requiredPhrases: ['Jeg vil gerne have et kort', 'Hvad skal jeg gøre?', 'Tak'] },
  { title: 'I parken', slug: 'in-park', category: 'social', level: 'A1', order: 9,
    description: 'Make small talk about the weather in the park.',
    scenarioPrompt: 'You are sitting in the park on a sunny day. An elderly person sits next to you and comments on the weather.',
    npcName: 'Else', npcRole: 'pensionist (pensioner)',
    requiredPhrases: ['Dejligt vejr i dag', 'Ja, solen skinner', 'Hav en god dag'] },
  { title: 'Fortælle om din familie', slug: 'about-family', category: 'social', level: 'A1', order: 10,
    description: 'Talk about your family in simple Danish.',
    scenarioPrompt: 'A new friend asks about your family. Tell them who is in your family.',
    npcName: 'Laura', npcRole: 'ny ven (new friend)',
    requiredPhrases: ['Jeg har en bror', 'Min mor hedder', 'Vi bor i Danmark'] },

  //╔══════════════════════════════════════════════════════════════╗
  //║  A2 — 20 missions (Elementary)                             ║
  //╚══════════════════════════════════════════════════════════════╝
  { title: 'Ring til lægen', slug: 'call-the-doctor', category: 'health', level: 'A2', order: 1,
    description: 'Call the doctor to book an appointment.',
    scenarioPrompt: 'You feel sick with a sore throat and fever. Call your doctor to book an appointment.',
    npcName: 'Mette', npcRole: 'lægesekretær (doctor receptionist)',
    requiredPhrases: ['Jeg er syg', 'Jeg har ondt i halsen', 'Jeg vil gerne bestille en tid'] },
  { title: 'Tal med din udlejer', slug: 'talk-to-landlord', category: 'housing', level: 'A2', order: 2,
    description: 'Tell your landlord about a problem in the apartment.',
    scenarioPrompt: 'The heating in your apartment stopped working. Call your landlord.',
    npcName: 'Søren', npcRole: 'udlejer (landlord)',
    requiredPhrases: ['Varmen virker ikke', 'Det er meget koldt', 'Hvornår kan du komme?'] },
  { title: 'Smalltalk med kollega', slug: 'small-talk-coworker', category: 'social', level: 'A2', order: 3,
    description: 'Small talk with a colleague during lunch.',
    scenarioPrompt: 'Lunch break at work. Chat with a colleague about the weekend.',
    npcName: 'Anna', npcRole: 'kollega (colleague)',
    requiredPhrases: ['Hvordan går det?', 'Hvad lavede du i weekenden?', 'Det lyder hyggeligt'] },
  { title: 'Købe medicin på apoteket', slug: 'buy-medicine', category: 'health', level: 'A2', order: 4,
    description: 'Ask for medicine at the pharmacy.',
    scenarioPrompt: 'You have a headache and need medicine. Go to the pharmacy.',
    npcName: 'Nina', npcRole: 'apoteker (pharmacist)',
    requiredPhrases: ['Jeg har hovedpine', 'Har I noget mod hovedpine?', 'Hvor meget koster det?'] },
  { title: 'Bestille tid hos tandlægen', slug: 'dentist-appointment', category: 'health', level: 'A2', order: 5,
    description: 'Book a dentist appointment.',
    scenarioPrompt: 'You have a toothache. Call the dentist to book an appointment.',
    npcName: 'Camilla', npcRole: 'tandlægesekretær (dentist receptionist)',
    requiredPhrases: ['Jeg har ondt i tanden', 'Hvornår har I en tid?', 'Kan jeg komme i morgen?'] },
  { title: 'Møde til tiden', slug: 'on-time-meeting', category: 'work', level: 'A2', order: 6,
    description: 'Explain you are late for a meeting.',
    scenarioPrompt: 'The bus is delayed and you are late for a meeting. Call your colleague to explain.',
    npcName: 'Peter', npcRole: 'kollega (colleague)',
    requiredPhrases: ['Bussen er forsinket', 'Jeg kommer lidt for sent', 'Vi ses om 10 minutter'] },
  { title: 'I fitness centeret', slug: 'at-gym', category: 'social', level: 'A2', order: 7,
    description: 'Ask about membership at a gym.',
    scenarioPrompt: 'You want to join a gym. Ask the receptionist about prices and opening hours.',
    npcName: 'Rasmus', npcRole: 'receptionist i fitnesscenter (gym receptionist)',
    requiredPhrases: ['Hvad koster et medlemskab?', 'Hvornår har I åbent?', 'Hvordan melder jeg mig ind?'] },
  { title: 'Spørge om husregler', slug: 'house-rules', category: 'housing', level: 'A2', order: 8,
    description: 'Ask your landlord about house rules.',
    scenarioPrompt: 'You just moved into a new apartment. Ask the landlord about parking, laundry, and quiet hours.',
    npcName: 'Morten', npcRole: 'udlejer (landlord)',
    requiredPhrases: ['Er der parkering?', 'Hvor er vaskeriet?', 'Hvornår er der stille?'] },
  { title: 'Tøjvask i vaskeriet', slug: 'laundry-room', category: 'housing', level: 'A2', order: 9,
    description: 'Ask a neighbour how to use the laundry room.',
    scenarioPrompt: 'You are in the shared laundry room for the first time. A neighbour is there and can help.',
    npcName: 'Jytte', npcRole: 'nabo (neighbour)',
    requiredPhrases: ['Hvordan bruger man vaskemaskinen?', 'Hvor længe tager det?', 'Mange tak'] },
  { title: 'I bageren', slug: 'at-bakery', category: 'shopping', level: 'A2', order: 10,
    description: 'Buy bread and pastries at a bakery.',
    scenarioPrompt: 'Go to a local bakery to buy fresh bread and pastries for breakfast.',
    npcName: 'Bente', npcRole: 'bager (baker)',
    requiredPhrases: ['Jeg vil gerne have et rugbrød', 'Har I wienerbrød?', 'Hvad koster det?'] },
  { title: 'Bestille et værelse', slug: 'book-hotel-room', category: 'shopping', level: 'A2', order: 11,
    description: 'Book a hotel room over the phone.',
    scenarioPrompt: 'You need a hotel room in Aarhus for one night. Call and book it.',
    npcName: 'Mia', npcRole: 'hotelreceptionist (hotel receptionist)',
    requiredPhrases: ['Jeg vil gerne booke et værelse', 'Hvad koster det pr. nat?', 'Er morgenmad inkluderet?'] },
  { title: 'Snak om vejret', slug: 'talk-weather', category: 'social', level: 'A2', order: 12,
    description: 'Have a simple conversation about the weather.',
    scenarioPrompt: 'You are waiting for the bus and someone comments on the rainy weather.',
    npcName: 'Bent', npcRole: 'buspassager (bus passenger)',
    requiredPhrases: ['Det regner meget i dag', 'Foråret er på vej', 'God dag til dig'] },
  { title: 'I svømmehallen', slug: 'at-swimming-pool', category: 'social', level: 'A2', order: 13,
    description: 'Ask about opening hours and prices at the swimming pool.',
    scenarioPrompt: 'You want to go swimming. Ask the lifeguard about prices and when it opens.',
    npcName: 'Troels', npcRole: 'livredder (lifeguard)',
    requiredPhrases: ['Hvad koster det at svømme?', 'Hvornår lukker I?', 'Er der en sauna?'] },
  { title: 'Finde den rigtige bus', slug: 'find-bus', category: 'social', level: 'A2', order: 14,
    description: 'Ask which bus goes to the city centre.',
    scenarioPrompt: 'You are at the bus stop and are unsure which bus goes to the city centre. Ask another passenger.',
    npcName: 'Fatima', npcRole: 'buspassager (bus passenger)',
    requiredPhrases: ['Undskyld, hvilken bus går til centrum?', 'Hvor tit kører den?', 'Tak for hjælpen'] },
  { title: 'Købe en gave', slug: 'buy-gift', category: 'shopping', level: 'A2', order: 15,
    description: 'Ask for help finding a gift in a shop.',
    scenarioPrompt: 'You need a birthday gift for a friend. Ask the shop assistant for help.',
    npcName: 'Louise', npcRole: 'butiksassistent (shop assistant)',
    requiredPhrases: ['Jeg leder efter en gave', 'Til en veninde', 'Hvad kan du anbefale?'] },
  { title: 'På posthuset', slug: 'at-post-office', category: 'shopping', level: 'A2', order: 16,
    description: 'Send a package at the post office.',
    scenarioPrompt: 'You need to send a package to your family abroad. Go to the post office.',
    npcName: 'Grethe', npcRole: 'postmedarbejder (post office worker)',
    requiredPhrases: ['Jeg vil gerne sende en pakke', 'Til Tyskland', 'Hvad koster det?'] },
  { title: 'Få nye nøgler', slug: 'get-new-keys', category: 'housing', level: 'A2', order: 17,
    description: 'Ask the landlord for new keys.',
    scenarioPrompt: 'You locked yourself out of your apartment. Call the landlord to get spare keys.',
    npcName: 'Karen', npcRole: 'udlejer (landlord)',
    requiredPhrases: ['Jeg har låst mig ude', 'Har du en ekstra nøgle?', 'Hvor kan jeg hente den?'] },
  { title: 'I genbrugsbutikken', slug: 'at-thrift-store', category: 'shopping', level: 'A2', order: 18,
    description: 'Shop at a second-hand store.',
    scenarioPrompt: 'You are at a second-hand store (genbrug). Ask about prices and sizes.',
    npcName: 'Vera', npcRole: 'medarbejder i genbrug (thrift store worker)',
    requiredPhrases: ['Hvor meget koster denne?', 'Har I en større størrelse?', 'Kan jeg prøve den?'] },
  { title: 'Snak om mad', slug: 'talk-about-food', category: 'social', level: 'A2', order: 19,
    description: 'Talk about your favourite foods.',
    scenarioPrompt: 'You are having lunch with a friend. Talk about what foods you like and dislike.',
    npcName: 'Aske', npcRole: 'ven (friend)',
    requiredPhrases: ['Kan du lide pizza?', 'Min yndlingsmad er', 'Smager det godt?'] },
  { title: 'Melde dig ind i en forening', slug: 'join-club', category: 'social', level: 'A2', order: 20,
    description: 'Ask about joining a local sports club.',
    scenarioPrompt: 'You want to join a local badminton club. Ask the coach about practice times and membership.',
    npcName: 'Lars', npcRole: 'træner (coach)',
    requiredPhrases: ['Jeg vil gerne spille badminton', 'Hvornår træner I?', 'Hvad koster det?'] },

  //╔══════════════════════════════════════════════════════════════╗
  //║  B1 — 30 missions (Intermediate)                           ║
  //╚══════════════════════════════════════════════════════════════╝
  { title: 'Forklar et bilproblem', slug: 'car-problem', category: 'shopping', level: 'B1', order: 1,
    description: 'Explain a car problem to a mechanic.',
    scenarioPrompt: 'Your car makes a strange noise when braking. Explain the issue to the mechanic.',
    npcName: 'Jens', npcRole: 'mekaniker (car mechanic)',
    requiredPhrases: ['Der er en mærkelig lyd', 'Når jeg bremser', 'Hvad koster det at reparere?'] },
  { title: 'Ring til internet support', slug: 'internet-support', category: 'technology', level: 'B1', order: 2,
    description: 'Call internet provider support about a connection issue.',
    scenarioPrompt: 'Your internet has been down for two days. Call support to troubleshoot.',
    npcName: 'Thomas', npcRole: 'internet support (support agent)',
    requiredPhrases: ['Mit internet virker ikke', 'Jeg har prøvet at genstarte', 'Hvornår kan I fikse det?'] },
  { title: 'Bank aftale', slug: 'bank-appointment', category: 'finance', level: 'B1', order: 3,
    description: 'Open a bank account at the bank.',
    scenarioPrompt: 'You just moved to Denmark and need to open a bank account. Meet with a bank advisor.',
    npcName: 'Camilla', npcRole: 'bankrådgiver (bank advisor)',
    requiredPhrases: ['Jeg vil gerne åbne en konto', 'Hvilke dokumenter skal jeg bruge?', 'Hvad er gebyrerne?'] },
  { title: 'På kommunen', slug: 'municipality-office', category: 'government', level: 'B1', order: 4,
    description: 'Update your address at the municipality.',
    scenarioPrompt: 'You moved to a new address. Visit the municipality office to update your address.',
    npcName: 'Pia', npcRole: 'kommunal sagsbehandler (caseworker)',
    requiredPhrases: ['Jeg er flyttet', 'Jeg vil gerne ændre min adresse', 'Hvilke dokumenter har jeg brug for?'] },
  { title: 'Jobsamtale', slug: 'job-interview', category: 'work', level: 'B1', order: 5,
    description: 'Participate in a job interview.',
    scenarioPrompt: 'You applied for a customer service job. The hiring manager interviews you.',
    npcName: 'Henrik', npcRole: 'ansættelseschef (hiring manager)',
    requiredPhrases: ['Jeg har erfaring med kundeservice', 'Jeg er god til at arbejde i team', 'Jeg vil gerne arbejde hos jer'] },
  { title: 'Bestille tid til syn', slug: 'car-inspection', category: 'shopping', level: 'B1', order: 6,
    description: 'Book a car inspection appointment.',
    scenarioPrompt: 'Your car needs its mandatory safety inspection (syn). Call the workshop to book a time.',
    npcName: 'Finn', npcRole: 'værkstedsassistent (workshop assistant)',
    requiredPhrases: ['Jeg skal have min bil til syn', 'Hvornår har I en ledig tid?', 'Hvor lang tid tager det?'] },
  { title: 'Forsikringsselskab', slug: 'insurance-call', category: 'finance', level: 'B1', order: 7,
    description: 'Call your insurance company about a claim.',
    scenarioPrompt: 'Your bike was stolen. Call your insurance company to report the theft and file a claim.',
    npcName: 'Ditte', npcRole: 'forsikringsmedarbejder (insurance agent)',
    requiredPhrases: ['Min cykel er blevet stjålet', 'Hvordan anmelder jeg et tyveri?', 'Hvad dækker forsikringen?'] },
  { title: 'Til samtale i jobcenter', slug: 'job-center', category: 'work', level: 'B1', order: 8,
    description: 'Speak with a job centre consultant.',
    scenarioPrompt: 'You are unemployed and have a meeting at the job centre. Discuss your job search plan.',
    npcName: 'Sanne', npcRole: 'jobkonsulent (job consultant)',
    requiredPhrases: ['Jeg søger arbejde', 'Jeg har sendt ansøgninger', 'Kan jeg få hjælp til et kursus?'] },
  { title: 'Barn syg i skolen', slug: 'sick-child-school', category: 'health', level: 'B1', order: 9,
    description: 'Call the school to report your child is sick.',
    scenarioPrompt: 'Your child is sick and cannot go to school. Call the school to report the absence.',
    npcName: 'Hanne', npcRole: 'skolesekretær (school secretary)',
    requiredPhrases: ['Min datter er syg', 'Hun kan ikke komme i skole i dag', 'Hvad skal jeg gøre med lektierne?'] },
  { title: 'Forældremøde', slug: 'parent-teacher-meeting', category: 'education', level: 'B1', order: 10,
    description: 'Attend a parent-teacher meeting.',
    scenarioPrompt: 'You attend a parent-teacher meeting at your childs school. Discuss their progress.',
    npcName: 'Lene', npcRole: 'klasselærer (class teacher)',
    requiredPhrases: ['Hvordan går det i skolen?', 'Hvad er han god til?', 'Er der noget han skal forbedre?'] },
  { title: 'Tilmelde barn til SFO', slug: 'after-school-care', category: 'education', level: 'B1', order: 11,
    description: 'Enrol your child in after-school care.',
    scenarioPrompt: 'You need to enrol your child in after-school care (SFO). Speak with the SFO leader.',
    npcName: 'Gitte', npcRole: 'SFO-leder (after-school care leader)',
    requiredPhrases: ['Jeg vil gerne tilmelde mit barn', 'Hvad koster det pr. måned?', 'Hvad laver børnene der?'] },
  { title: 'Opsige abonnement', slug: 'cancel-subscription', category: 'technology', level: 'B1', order: 12,
    description: 'Cancel a streaming subscription.',
    scenarioPrompt: 'You want to cancel your streaming service subscription. Call customer service.',
    npcName: 'David', npcRole: 'kundeservicemedarbejder (customer service)',
    requiredPhrases: ['Jeg vil gerne opsige mit abonnement', 'Hvad er opsigelsesperioden?', 'Hvorfor vil du opsige?'] },
  { title: 'Møde med bankrådgiver om lån', slug: 'loan-meeting', category: 'finance', level: 'B1', order: 13,
    description: 'Discuss a loan with your bank advisor.',
    scenarioPrompt: 'You want to take out a loan for a car. Meet with a bank advisor to discuss options.',
    npcName: 'Nikolaj', npcRole: 'bankrådgiver (bank advisor)',
    requiredPhrases: ['Jeg vil gerne låne penge til en bil', 'Hvad er renten?', 'Hvor lang er tilbagebetalingsperioden?'] },
  { title: 'På apoteket med recept', slug: 'prescription-pharmacy', category: 'health', level: 'B1', order: 14,
    description: 'Pick up a prescription at the pharmacy.',
    scenarioPrompt: 'The doctor sent a prescription to the pharmacy. Go pick it up and ask about dosage.',
    npcName: 'Stine', npcRole: 'farmakonom (pharmacy assistant)',
    requiredPhrases: ['Jeg skal hente en recept', 'Hvordan skal jeg tage medicinen?', 'Er der bivirkninger?'] },
  { title: 'Købe brugt bil', slug: 'buy-used-car', category: 'shopping', level: 'B1', order: 15,
    description: 'Ask about a used car for sale.',
    scenarioPrompt: 'You found a used car for sale online. Call the seller to ask about it.',
    npcName: 'Brian', npcRole: 'bilsælger (car seller)',
    requiredPhrases: ['Jeg ringer om den brugte bil', 'Hvor mange kilometer har den kørt?', 'Kan jeg komme og se den?'] },
  { title: 'Til læge med kronisk problem', slug: 'chronic-issue-doctor', category: 'health', level: 'B1', order: 16,
    description: 'Discuss an ongoing health issue with your doctor.',
    scenarioPrompt: 'You have had back pain for several weeks. Describe the problem to your doctor.',
    npcName: 'Dr. Nielsen', npcRole: 'læge (doctor)',
    requiredPhrases: ['Jeg har ondt i ryggen', 'Det har varet i flere uger', 'Hvad kan jeg gøre ved det?'] },
  { title: 'Problemer med nabo', slug: 'noisy-neighbour', category: 'housing', level: 'B1', order: 17,
    description: 'Talk to your neighbour about noise.',
    scenarioPrompt: 'Your neighbour plays loud music late at night. Knock on their door and talk about it politely.',
    npcName: 'Mikkel', npcRole: 'støjende nabo (noisy neighbour)',
    requiredPhrases: ['Undskyld, musikken er lidt høj', 'Det er sent', 'Kan du skrue ned?'] },
  { title: 'Bestille flybilletter', slug: 'book-flights', category: 'shopping', level: 'B1', order: 18,
    description: 'Book flights for a holiday.',
    scenarioPrompt: 'You want to book flights to Spain for your holiday. Call the travel agency.',
    npcName: 'Tanja', npcRole: 'rejseagent (travel agent)',
    requiredPhrases: ['Jeg vil gerne booke en rejse til Spanien', 'Hvad koster billetterne?', 'Er der direkte fly?'] },
  { title: 'Sygemelding', slug: 'sick-leave', category: 'work', level: 'B1', order: 19,
    description: 'Call your boss to report in sick.',
    scenarioPrompt: 'You woke up with a fever and cannot go to work. Call your boss to report sick.',
    npcName: 'Charlotte', npcRole: 'chef (boss)',
    requiredPhrases: ['Jeg er syg i dag', 'Jeg har feber', 'Jeg holder mig hjemme'] },
  { title: 'Lægeerklæring', slug: 'doctor-note', category: 'health', level: 'B1', order: 20,
    description: 'Ask your doctor for a medical certificate.',
    scenarioPrompt: 'Your employer needs a doctors note for your sick leave. Ask the doctor.',
    npcName: 'Dr. Poulsen', npcRole: 'læge (doctor)',
    requiredPhrases: ['Jeg har brug for en lægeerklæring', 'Arbejdsgiveren kræver det', 'Hvornår er den klar?'] },
  { title: 'Indgive selvangivelse', slug: 'tax-return', category: 'finance', level: 'B1', order: 21,
    description: 'Ask for help with your tax return.',
    scenarioPrompt: 'You find the Danish tax system complicated. Call SKAT for help with your tax return.',
    npcName: 'Anders', npcRole: 'SKAT-medarbejder (tax officer)',
    requiredPhrases: ['Jeg har brug for hjælp til selvangivelse', 'Hvordan indberetter jeg?', 'Hvad er fradrag?'] },
  { title: 'Til tandlæge', slug: 'dentist-checkup', category: 'health', level: 'B1', order: 22,
    description: 'Attend a routine dentist checkup.',
    scenarioPrompt: 'You are at the dentist for a routine checkup. The dentist examines your teeth.',
    npcName: 'Dr. Møller', npcRole: 'tandlæge (dentist)',
    requiredPhrases: ['Jeg er kommet til kontrol', 'Det gør lidt ondt her', 'Børster jeg tænder nok?'] },
  { title: 'Skrive en e-mail til læreren', slug: 'email-teacher', category: 'education', level: 'B1', order: 23,
    description: 'Write an email to a teacher about coursework.',
    scenarioPrompt: 'You are taking a Danish course and need to ask your teacher about an assignment.',
    npcName: 'Marianne', npcRole: 'dansklærer (Danish teacher)',
    requiredPhrases: ['Jeg har et spørgsmål om opgaven', 'Hvornår er deadline?', 'Kan jeg få feedback?'] },
  { title: 'Tilmelde sig et kursus', slug: 'sign-up-course', category: 'education', level: 'B1', order: 24,
    description: 'Sign up for a professional course.',
    scenarioPrompt: 'You want to take a professional development course. Call the adult education centre.',
    npcName: 'Jesper', npcRole: 'kursusadministrator (course administrator)',
    requiredPhrases: ['Jeg vil gerne tilmelde mig et kursus', 'Hvad koster det?', 'Er der nogle forudsætninger?'] },
  { title: 'Leje en bil', slug: 'rent-car', category: 'shopping', level: 'B1', order: 25,
    description: 'Rent a car for a weekend trip.',
    scenarioPrompt: 'You want to rent a car for a weekend trip to Jylland. Call the rental company.',
    npcName: 'Sven', npcRole: 'biludlejer (car rental agent)',
    requiredPhrases: ['Jeg vil gerne leje en bil til weekenden', 'Hvad koster det pr. dag?', 'Er forsikring inkluderet?'] },
  { title: 'Politi anmeldelse', slug: 'police-report', category: 'government', level: 'B1', order: 26,
    description: 'Report a theft to the police.',
    scenarioPrompt: 'Your wallet was stolen at the train station. Go to the police station to report it.',
    npcName: 'Birgitte', npcRole: 'politibetjent (police officer)',
    requiredPhrases: ['Jeg vil gerne anmelde et tyveri', 'Min pung er blevet stjålet', 'Hvad skal jeg gøre nu?'] },
  { title: 'Opsige fitness abonnement', slug: 'cancel-gym', category: 'technology', level: 'B1', order: 27,
    description: 'Cancel your gym membership.',
    scenarioPrompt: 'You are moving to another city and need to cancel your gym membership.',
    npcName: 'Markus', npcRole: 'fitnesskonsulent (fitness consultant)',
    requiredPhrases: ['Jeg skal opsige mit medlemskab', 'Jeg flytter til en anden by', 'Hvad er opsigelsesvarslen?'] },
  { title: 'Arrangere en fødselsdag', slug: 'plan-birthday', category: 'social', level: 'B1', order: 28,
    description: 'Plan a birthday party with a friend.',
    scenarioPrompt: 'You want to plan a surprise birthday party for a mutual friend. Discuss ideas.',
    npcName: 'Sofie', npcRole: 'veninde (friend)',
    requiredPhrases: ['Lad os planlægge en overraskelsesfest', 'Jeg kan sørge for kage', 'Hvem skal inviteres?'] },
  { title: 'Melde flytning', slug: 'register-move', category: 'government', level: 'B1', order: 29,
    description: 'Register a change of address online.',
    scenarioPrompt: 'You moved to a new address and need to register it with the national register. Call for help.',
    npcName: 'Britt', npcRole: 'borgerservice medarbejder (citizen service)',
    requiredPhrases: ['Jeg er flyttet til en ny adresse', 'Jeg vil gerne registrere min flytning', 'Hvordan gør jeg online?'] },
  { title: 'Bestille en taxi', slug: 'order-taxi', category: 'shopping', level: 'B1', order: 30,
    description: 'Order a taxi over the phone.',
    scenarioPrompt: 'You need to get to the airport early in the morning. Order a taxi the night before.',
    npcName: 'Viktor', npcRole: 'taxachauffør (taxi driver)',
    requiredPhrases: ['Jeg vil gerne bestille en taxi', 'Til lufthavnen kl. 6', 'Hvad koster turen?'] },

  //╔══════════════════════════════════════════════════════════════╗
  //║  B2 — 40 missions (Upper Intermediate)                     ║
  //╚══════════════════════════════════════════════════════════════╝
  { title: 'Ejendomsmægler møde', slug: 'real-estate-agent', category: 'housing', level: 'B2', order: 1,
    description: 'Discuss buying an apartment with a real estate agent.',
    scenarioPrompt: 'You want to buy an apartment in Copenhagen. Meet with a real estate agent.',
    npcName: 'Michael', npcRole: 'ejendomsmægler (real estate agent)',
    requiredPhrases: ['Jeg leder efter en lejlighed', 'Hvad er prisen?', 'Hvornår kan jeg se den?'] },
  { title: 'Til banken med realkreditlån', slug: 'mortgage-meeting', category: 'finance', level: 'B2', order: 2,
    description: 'Discuss mortgage options with your bank.',
    scenarioPrompt: 'You want to buy a home and need a mortgage. Meet with your bank for a detailed discussion.',
    npcName: 'Louise', npcRole: 'realkreditrådgiver (mortgage advisor)',
    requiredPhrases: ['Jeg vil købe en bolig', 'Hvad er renten på realkreditlån?', 'Hvor meget kan jeg låne?'] },
  { title: 'Til jobsamtale, lederstilling', slug: 'manager-interview', category: 'work', level: 'B2', order: 3,
    description: 'Attend a job interview for a management position.',
    scenarioPrompt: 'You applied for a team leader role. This is a second-round interview with the department head.',
    npcName: 'Claus', npcRole: 'afdelingsleder (department head)',
    requiredPhrases: ['Jeg har ledelseserfaring', 'Jeg motiverer mit team', 'Jeg kan håndtere konflikter'] },
  { title: 'Udbetaling af pension', slug: 'pension-payout', category: 'finance', level: 'B2', order: 4,
    description: 'Discuss pension options with your provider.',
    scenarioPrompt: 'You are changing jobs and need to decide what to do with your pension. Call your pension company.',
    npcName: 'Erik', npcRole: 'pensionsrådgiver (pension advisor)',
    requiredPhrases: ['Jeg skifter job', 'Hvad skal jeg gøre med min pension?', 'Hvad er fordelene og ulemperne?'] },
  { title: 'Fagforening møde', slug: 'union-meeting', category: 'work', level: 'B2', order: 5,
    description: 'Discuss workplace issues with your union representative.',
    scenarioPrompt: 'You have concerns about your work contract. Meet with your union representative to review it.',
    npcName: 'Bente', npcRole: 'fagforeningsrepræsentant (union rep)',
    requiredPhrases: ['Jeg har spørgsmål om min kontrakt', 'Hvad er standarden?', 'Er vilkårene rimelige?'] },
  { title: 'Til læge med stress', slug: 'stress-doctor', category: 'health', level: 'B2', order: 6,
    description: 'Discuss stress and mental health with your doctor.',
    scenarioPrompt: 'You have been feeling stressed and overwhelmed. Talk to your doctor about it.',
    npcName: 'Dr. Hansen', npcRole: 'praktiserende læge (GP)',
    requiredPhrases: ['Jeg stresser meget på arbejdet', 'Jeg sover dårligt', 'Hvad kan jeg gøre?'] },
  { title: 'Fornyelse af opholdstilladelse', slug: 'renew-residence', category: 'government', level: 'B2', order: 7,
    description: 'Apply to renew your residence permit.',
    scenarioPrompt: 'Your residence permit is expiring. Call the immigration service about renewal.',
    npcName: 'Nadia', npcRole: 'medarbejder i Udlændingestyrelsen (immigration officer)',
    requiredPhrases: ['Min opholdstilladelse udløber', 'Hvordan fornyer jeg den?', 'Hvilke dokumenter skal jeg sende?'] },
  { title: 'Indgive klage til kommunen', slug: 'complain-municipality', category: 'government', level: 'B2', order: 8,
    description: 'File a complaint with the municipality.',
    scenarioPrompt: 'You have been denied a benefit and believe it was a mistake. File a formal complaint.',
    npcName: 'Mette', npcRole: 'klagesagsbehandler (complaint handler)',
    requiredPhrases: ['Jeg vil gerne klage over afgørelsen', 'Jeg fik afslag på min ansøgning', 'Hvad er klagefristen?'] },
  { title: 'Til netværksarrangement', slug: 'networking-event', category: 'work', level: 'B2', order: 9,
    description: 'Network at a professional event.',
    scenarioPrompt: 'You are at a networking event for IT professionals. Introduce yourself and make connections.',
    npcName: 'Morten', npcRole: 'konsulent i IT (IT consultant)',
    requiredPhrases: ['Hvad arbejder du med?', 'Jeg er specialist i', 'Lad os udveksle kort'] },
  { title: 'Tilskud fra kommunen', slug: 'municipality-benefit', category: 'government', level: 'B2', order: 10,
    description: 'Apply for financial support from the municipality.',
    scenarioPrompt: 'You need temporary financial assistance. Meet with a caseworker at the municipality.',
    npcName: 'Rikke', npcRole: 'socialrådgiver (social worker)',
    requiredPhrases: ['Jeg har brug for økonomisk hjælp', 'Hvad har jeg ret til?', 'Hvordan søger jeg?'] },
  { title: 'Konflikt med arbejdsgiver', slug: 'workplace-conflict', category: 'work', level: 'B2', order: 11,
    description: 'Resolve a conflict with your manager.',
    scenarioPrompt: 'You had a disagreement with your manager about your workload. Request a meeting to resolve it.',
    npcName: 'Tina', npcRole: 'HR-leder (HR manager)',
    requiredPhrases: ['Jeg har haft en uoverensstemmelse med min chef', 'Jeg føler mig overbebyrdet', 'Kan I hjælpe med at mægle?'] },
  { title: 'Til læge med allergi', slug: 'allergy-doctor', category: 'health', level: 'B2', order: 12,
    description: 'Get tested and treated for allergies.',
    scenarioPrompt: 'You suspect you have seasonal allergies. Describe your symptoms to the doctor.',
    npcName: 'Dr. Svendsen', npcRole: 'speciallæge (specialist)',
    requiredPhrases: ['Jeg nyser hele tiden om foråret', 'Mine øjne klør', 'Kan jeg blive testet for allergi?'] },
  { title: 'Underskrive huslejekontrakt', slug: 'sign-lease', category: 'housing', level: 'B2', order: 13,
    description: 'Review and sign a rental contract.',
    scenarioPrompt: 'You found an apartment. The landlord sends you the lease contract to review and sign.',
    npcName: 'Ulla', npcRole: 'udlejer (landlord)',
    requiredPhrases: ['Jeg har læst kontrakten', 'Jeg har et spørgsmål om opsigelsesvarsel', 'Kan jeg få en gennemgang?'] },
  { title: 'Til frivillig arbejde', slug: 'volunteer-apply', category: 'social', level: 'B2', order: 14,
    description: 'Apply to volunteer at a local organisation.',
    scenarioPrompt: 'You want to volunteer at a local food bank. Call to discuss how you can help.',
    npcName: 'Anne Mette', npcRole: 'frivilligkoordinator (volunteer coordinator)',
    requiredPhrases: ['Jeg vil gerne være frivillig', 'Hvad har I brug for hjælp til?', 'Hvor mange timer om ugen?'] },
  { title: 'Forhandle løn', slug: 'salary-negotiation', category: 'work', level: 'B2', order: 15,
    description: 'Negotiate your salary for a new job.',
    scenarioPrompt: 'You received a job offer. Call the HR manager to negotiate the salary.',
    npcName: 'Helle', npcRole: 'HR-chef (HR manager)',
    requiredPhrases: ['Jeg er meget interesseret i stillingen', 'Men jeg havde forventet en højere løn', 'Kan vi forhandle?'] },
  { title: 'Boligsøgning', slug: 'housing-search', category: 'housing', level: 'B2', order: 16,
    description: 'Register on the municipal housing list.',
    scenarioPrompt: 'You want to register for a rent-controlled apartment (almen bolig). Call the housing agency.',
    npcName: 'Mona', npcRole: 'boligsocialmedarbejder (housing officer)',
    requiredPhrases: ['Jeg vil gerne skrive mig op til en bolig', 'Hvor lang er ventetiden?', 'Hvilke boliger har I?'] },
  { title: 'Søge om SU', slug: 'apply-su', category: 'education', level: 'B2', order: 17,
    description: 'Apply for student financial support (SU).',
    scenarioPrompt: 'You have been accepted to a Danish university. Call to ask about SU eligibility.',
    npcName: 'Claus', npcRole: 'SU-medarbejder (student grants officer)',
    requiredPhrases: ['Jeg skal til at læse på universitetet', 'Er jeg berettiget til SU?', 'Hvordan ansøger jeg?'] },
  { title: 'Bestille tid hos psykolog', slug: 'psychologist-appointment', category: 'health', level: 'B2', order: 18,
    description: 'Book an appointment with a psychologist.',
    scenarioPrompt: 'You have been feeling anxious. Call a psychologist to book an appointment.',
    npcName: 'Mie', npcRole: 'psykologsekretær (psychology clinic)',
    requiredPhrases: ['Jeg har brug for at tale med en psykolog', 'Jeg har angst', 'Hvornår har I en tid?'] },
  { title: 'Til akademisk samtale', slug: 'academic-advising', category: 'education', level: 'B2', order: 19,
    description: 'Discuss your study plan with a university advisor.',
    scenarioPrompt: 'You are planning your semester courses. Meet with your academic advisor.',
    npcName: 'Andreas', npcRole: 'studievejleder (academic advisor)',
    requiredPhrases: ['Jeg vil gerne planlægge mit semester', 'Hvilke kurser kan du anbefale?', 'Hvordan er eksamensformen?'] },
  { title: 'Kontakte a-kasse', slug: 'unemployment-fund', category: 'work', level: 'B2', order: 20,
    description: 'Sign up for unemployment benefits.',
    scenarioPrompt: 'You lost your job. Call your unemployment fund (a-kasse) to sign up for benefits.',
    npcName: 'Susanne', npcRole: 'a-kasse medarbejder (unemployment fund officer)',
    requiredPhrases: ['Jeg er blevet opsagt', 'Jeg vil gerne have dagpenge', 'Hvilke papirer skal jeg indsende?'] },
  { title: 'Indbrud i hjemmet', slug: 'burglary-report', category: 'housing', level: 'B2', order: 21,
    description: 'Report a burglary to the police.',
    scenarioPrompt: 'Someone broke into your home while you were away. Report it to the police.',
    npcName: 'Jens', npcRole: 'politiassistent (police assistant)',
    requiredPhrases: ['Der har været indbrud i mit hjem', 'De har stjålet smykker og en computer', 'Kan jeg få et sagsnummer?'] },
  { title: 'Til banken investering', slug: 'investment-advice', category: 'finance', level: 'B2', order: 22,
    description: 'Discuss investment options with your bank.',
    scenarioPrompt: 'You have some savings and want to invest. Meet with a bank investment advisor.',
    npcName: 'Finn', npcRole: 'investeringsrådgiver (investment advisor)',
    requiredPhrases: ['Jeg vil gerne investere mine opsparinger', 'Hvad er risikoen?', 'Hvilke fonde anbefaler du?'] },
  { title: 'Bestille tid hos øjenlæge', slug: 'eye-doctor', category: 'health', level: 'B2', order: 23,
    description: 'Book an eye exam.',
    scenarioPrompt: 'Your vision has gotten worse. Call the eye doctor for an appointment.',
    npcName: 'Mette', npcRole: 'øjenlægesekretær (eye clinic)',
    requiredPhrases: ['Jeg ser dårligere på det ene øje', 'Jeg har brug for en synstest', 'Hvor lang tid tager det?'] },
  { title: 'Til fødselsforberedelse', slug: 'childbirth-class', category: 'health', level: 'B2', order: 24,
    description: 'Sign up for a childbirth preparation class.',
    scenarioPrompt: 'You and your partner are expecting a baby. Call the hospital to sign up for classes.',
    npcName: 'Jordemoder Grethe', npcRole: 'jordemoder (midwife)',
    requiredPhrases: ['Jeg er gravid', 'Jeg vil gerne tilmelde mig fødselsforberedelse', 'Hvornår starter holdet?'] },
  { title: 'Til samtale om børnehaveplads', slug: 'kindergarten-placement', category: 'education', level: 'B2', order: 25,
    description: 'Discuss kindergarten placement for your child.',
    scenarioPrompt: 'Your child needs a kindergarten place. Speak with the municipality about options.',
    npcName: 'Pia', npcRole: 'pladsanvisning (placement officer)',
    requiredPhrases: ['Mit barn har brug for en børnehaveplads', 'Hvad er ventetiden?', 'Hvilke institutioner kan I tilbyde?'] },
  { title: 'Til ejendomsvurdering', slug: 'property-valuation', category: 'finance', level: 'B2', order: 26,
    description: 'Get your property valued.',
    scenarioPrompt: 'You want to sell your house. Meet with an appraiser for a valuation.',
    npcName: 'Bjarne', npcRole: 'ejendomsmægler og valuar (appraiser)',
    requiredPhrases: ['Jeg overvejer at sælge mit hus', 'Hvad er det værd?', 'Hvordan er markedet lige nu?'] },
  { title: 'Til jobsamtale, offentlig stilling', slug: 'public-sector-interview', category: 'work', level: 'B2', order: 27,
    description: 'Attend a job interview for a public sector position.',
    scenarioPrompt: 'You applied for a job at the municipality. The interview panel consists of three people.',
    npcName: 'Bettina', npcRole: 'afdelingschef (department manager)',
    requiredPhrases: ['Jeg har erfaring fra det offentlige', 'Jeg kender forvaltningsloven', 'Jeg er god til sagsbehandling'] },
  { title: 'Undersøge erstatningskrav', slug: 'compensation-claim', category: 'government', level: 'B2', order: 28,
    description: 'File a compensation claim for damages.',
    scenarioPrompt: 'You slipped on an icy sidewalk and broke your arm. Ask about compensation from the municipality.',
    npcName: 'Kirsten', npcRole: 'erstatningsmedarbejder (claims officer)',
    requiredPhrases: ['Jeg faldt på et glat fortov', 'Jeg brækkede armen', 'Har jeg krav på erstatning?'] },
  { title: 'Til forældreråd', slug: 'parent-council', category: 'education', level: 'B2', order: 29,
    description: 'Participate in the school parent council.',
    scenarioPrompt: 'You are on the parent council at your childs school. Discuss fundraising ideas.',
    npcName: 'Trine', npcRole: 'forældrerådsformand (parent council chair)',
    requiredPhrases: ['Vi skal planlægge en skolefest', 'Hvad skal pengene bruges til?', 'Hvem tager ansvar for?'] },
  { title: 'Til læge med hudproblemer', slug: 'skin-doctor', category: 'health', level: 'B2', order: 30,
    description: 'See a dermatologist about a skin condition.',
    scenarioPrompt: 'You have a persistent rash. The GP referred you to a dermatologist.',
    npcName: 'Dr. Bang', npcRole: 'hudlæge (dermatologist)',
    requiredPhrases: ['Jeg har haft udslæt i flere måneder', 'Det klør om natten', 'Hvad kan det være?'] },
  { title: 'Til ansættelsessamtale for SU', slug: 'su-committee', category: 'education', level: 'B2', order: 31,
    description: 'Attend a SU committee interview.',
    scenarioPrompt: 'Your SU application requires an interview. Discuss your study progress.',
    npcName: 'Lise', npcRole: 'SU-udvalgsmedlem (SU committee member)',
    requiredPhrases: ['Jeg følger studieplanen', 'Jeg bestod alle eksamener sidste år', 'Jeg forventer at være færdig til tiden'] },
  { title: 'Købe sommerhus', slug: 'buy-summer-house', category: 'shopping', level: 'B2', order: 32,
    description: 'Inquire about buying a summer house.',
    scenarioPrompt: 'You want to buy a summer house by the coast. Call the real estate agent.',
    npcName: 'Niels', npcRole: 'ejendomsmægler (real estate agent)',
    requiredPhrases: ['Jeg leder efter et sommerhus', 'Hvad er prislejet?', 'Er der direkte adgang til stranden?'] },
  { title: 'Indsamling til velgørenhed', slug: 'charity-fundraising', category: 'social', level: 'B2', order: 33,
    description: 'Organise a charity event.',
    scenarioPrompt: 'You want to organise a charity run. Discuss logistics with the community centre.',
    npcName: 'Helle', npcRole: 'kulturhusleder (community centre manager)',
    requiredPhrases: ['Jeg vil gerne arrangere et velgørenhedsløb', 'Kan vi bruge jeres lokaler?', 'Hvad skal vi bruge til arrangementet?'] },
  { title: 'Til borgermøde', slug: 'town-hall', category: 'government', level: 'B2', order: 34,
    description: 'Speak at a town hall meeting.',
    scenarioPrompt: 'The municipality is planning to build a new road near your home. Speak at the town hall meeting.',
    npcName: 'Borgmester Jensen', npcRole: 'borgmester (mayor)',
    requiredPhrases: ['Jeg er bekymret for støjniveauet', 'Har I overvejet alternative ruter?', 'Hvornår er byggeriet planlagt?'] },
  { title: 'Bestille specialmad i restaurant', slug: 'special-diet-restaurant', category: 'social', level: 'B2', order: 35,
    description: 'Order food with dietary restrictions at a restaurant.',
    scenarioPrompt: 'You have a gluten allergy. Call a restaurant ahead to ask about gluten-free options.',
    npcName: 'Kasper', npcRole: 'restauratør (restaurant owner)',
    requiredPhrases: ['Jeg har glutenallergi', 'Har I glutenfri muligheder?', 'Kan I tilpasse retterne?'] },
  { title: 'Få børnepasning', slug: 'childcare-arrangement', category: 'social', level: 'B2', order: 36,
    description: 'Arrange childcare with a neighbour.',
    scenarioPrompt: 'You need someone to watch your child after school. Talk to your neighbour about it.',
    npcName: 'Hanne', npcRole: 'nabo (neighbour)',
    requiredPhrases: ['Har du mulighed for at passe min datter?', 'Det er kun to timer efter skole', 'Jeg betaler selvfølgelig'] },
  { title: 'Til samtale om revalidering', slug: 'rehabilitation-meeting', category: 'government', level: 'B2', order: 37,
    description: 'Discuss job rehabilitation with the municipality.',
    scenarioPrompt: 'After a long illness, you need help returning to the job market. Meet with your job consultant.',
    npcName: 'Lisbeth', npcRole: 'revalideringskonsulent (rehabilitation consultant)',
    requiredPhrases: ['Jeg har været syg i lang tid', 'Jeg er klar til at vende tilbage til arbejdsmarkedet', 'Hvilken støtte kan jeg få?'] },
  { title: 'Søge om byggetilladelse', slug: 'building-permit', category: 'government', level: 'B2', order: 38,
    description: 'Apply for a building permit.',
    scenarioPrompt: 'You want to build a terrace on your house. Call the municipality about a building permit.',
    npcName: 'Bjarne', npcRole: 'byggesagsbehandler (building officer)',
    requiredPhrases: ['Jeg vil gerne bygge en terrasse', 'Har jeg brug for en byggetilladelse?', 'Hvordan ansøger jeg?'] },
  { title: 'Til faglig opdatering', slug: 'professional-update', category: 'work', level: 'B2', order: 39,
    description: 'Attend a professional development seminar.',
    scenarioPrompt: 'Your industry is changing rapidly. You want to attend a seminar to update your skills.',
    npcName: 'Pernille', npcRole: 'kursusleder (course leader)',
    requiredPhrases: ['Jeg har brug for at opdatere mine kompetencer', 'Hvad dækker seminaret?', 'Får jeg et bevis?'] },
  { title: 'Indgive en ansøgning om dispensation', slug: 'dispensation-apply', category: 'education', level: 'B2', order: 40,
    description: 'Apply for a dispensation at university.',
    scenarioPrompt: 'You need an extension on your thesis deadline. Apply for a dispensation.',
    npcName: 'Stine', npcRole: 'studieadministration (student admin)',
    requiredPhrases: ['Jeg har brug for en dispensation', 'Min deadline er for stram', 'Hvad skal jeg vedlægge ansøgningen?'] },

  //╔══════════════════════════════════════════════════════════════╗
  //║  C1 — 50 missions (Advanced)                               ║
  //╚══════════════════════════════════════════════════════════════╝
  { title: 'Borgerskabssamtale', slug: 'citizenship-interview', category: 'citizenship', level: 'C1', order: 1,
    description: 'Prepare for the Danish citizenship interview.',
    scenarioPrompt: 'Your citizenship interview. The officer asks about Danish culture, history, and society.',
    npcName: 'Lars', npcRole: 'borgerskabsmedarbejder (citizenship officer)',
    requiredPhrases: ['Danmark er et konstitutionelt monarki', 'Grundloven er fra 1849', 'Jeg ønsker at blive dansk statsborger'] },
  { title: 'Forsvar din ph.d.-afhandling', slug: 'phd-defense', category: 'education', level: 'C1', order: 2,
    description: 'Defend your PhD thesis.',
    scenarioPrompt: 'You are defending your PhD thesis in front of the assessment committee.',
    npcName: 'Professor Nielsen', npcRole: 'bedømmelsesudvalgsformand (committee chair)',
    requiredPhrases: ['Min forskning viser', 'Jeg har anvendt en kvalitativ metode', 'Implikationerne er betydelige'] },
  { title: 'Forretningsforhandling', slug: 'business-negotiation', category: 'work', level: 'C1', order: 3,
    description: 'Negotiate a business contract.',
    scenarioPrompt: 'You are negotiating a partnership agreement with a Danish company.',
    npcName: 'Jacob', npcRole: 'direktør (company director)',
    requiredPhrases: ['Vores betingelser er', 'Vi kan tilbyde en rabat ved', 'Lad os finde et kompromis'] },
  { title: 'Debat på borgermøde', slug: 'public-debate', category: 'government', level: 'C1', order: 4,
    description: 'Participate in a heated public debate.',
    scenarioPrompt: 'A controversial construction project is being debated at the town hall. Voice your opinion.',
    npcName: 'Karen', npcRole: 'byrådsmedlem (city council member)',
    requiredPhrases: ['Jeg er principielt imod', 'Miljøpåvirkningen er bekymrende', 'Jeg opfordrer til en folkeafstemning'] },
  { title: 'Acceptere et jobtilbud', slug: 'accept-job-offer', category: 'work', level: 'C1', order: 5,
    description: 'Negotiate terms and accept a job offer.',
    scenarioPrompt: 'You received a job offer. Negotiate the terms, including pension, vacation, and work-from-home policy.',
    npcName: 'Mette', npcRole: 'HR-direktør (HR director)',
    requiredPhrases: ['Jeg accepterer gerne tilbuddet', 'Men jeg ønsker flere hjemmearbejdsdage', 'Kan vi justere pensionsordningen?'] },
  { title: 'Henvendelse til ombudsmanden', slug: 'ombudsman-complaint', category: 'government', level: 'C1', order: 6,
    description: 'File a formal complaint with the Parliamentary Ombudsman.',
    scenarioPrompt: 'You believe a public authority treated you unfairly. Write to the Ombudsman.',
    npcName: 'Kontorchef', npcRole: 'ombudsmandskonsulent (ombudsman consultant)',
    requiredPhrases: ['Jeg påklager en afgørelse', 'Jeg mener der er begået en fejl', 'Sagen drejer sig om'] },
  { title: 'Foredrag på din virksomhed', slug: 'company-presentation', category: 'work', level: 'C1', order: 7,
    description: 'Give a professional presentation at work.',
    scenarioPrompt: 'You need to present the quarterly results to the board of directors.',
    npcName: 'Bestyrelsesformand', npcRole: 'bestyrelsesformand (board chair)',
    requiredPhrases: ['Kvartalsresultaterne viser', 'Vores omsætning er steget med', 'Jeg anbefaler, at vi'] },
  { title: 'Skatteadvokat møde', slug: 'tax-lawyer', category: 'finance', level: 'C1', order: 8,
    description: 'Discuss a complex tax issue with your lawyer.',
    scenarioPrompt: 'You have a cross-border tax issue. Meet with a tax lawyer to discuss your situation.',
    npcName: 'Thomas', npcRole: 'skatteadvokat (tax lawyer)',
    requiredPhrases: ['Jeg har indtægter fra udlandet', 'Hvordan undgår jeg dobbeltbeskatning?', 'Hvad er SKATs praksis?'] },
  { title: 'Klage til Ankestyrelsen', slug: 'appeal-board', category: 'government', level: 'C1', order: 9,
    description: 'Appeal a municipality decision to the Appeals Board.',
    scenarioPrompt: 'Your benefit application was rejected. You believe the decision was wrong and appeal it.',
    npcName: 'Sagsbehandler', npcRole: 'Ankestyrelsens medarbejder (appeals officer)',
    requiredPhrases: ['Jeg påklager afgørelsen', 'Jeg har nye oplysninger', 'Hvor lang tid tager en klagesag?'] },
  { title: 'Deltage i en radiodebat', slug: 'radio-debate', category: 'social', level: 'C1', order: 10,
    description: 'Participate in a live radio debate.',
    scenarioPrompt: 'You are invited to a live radio debate about integration in Denmark.',
    npcName: 'Vært', npcRole: 'radiovært (radio host)',
    requiredPhrases: ['Fra mit perspektiv', 'Integration handler om', 'Jeg er uenig i, at'] },
  { title: 'Ansøgning om forskningsmidler', slug: 'research-grant', category: 'education', level: 'C1', order: 11,
    description: 'Apply for a research grant.',
    scenarioPrompt: 'You are applying for a major research grant. Discuss your proposal with the funding committee.',
    npcName: 'Forskningsleder', npcRole: 'forskningsrådsmedlem (research council member)',
    requiredPhrases: ['Mit projekt adresserer', 'Metoden er innovativ fordi', 'De forventede resultater er'] },
  { title: 'Advokat møde skilsmisse', slug: 'divorce-lawyer', category: 'social', level: 'C1', order: 12,
    description: 'Meet with a lawyer about divorce proceedings.',
    scenarioPrompt: 'You are going through a divorce. Meet with your lawyer to discuss the process.',
    npcName: 'Helle', npcRole: 'familieretsadvokat (family lawyer)',
    requiredPhrases: ['Vi er blevet enige om separation', 'Hvordan fordeler vi ejendelene?', 'Hvad med forældremyndigheden?'] },
  { title: 'Til jobsamtale, direktørstilling', slug: 'ceo-interview', category: 'work', level: 'C1', order: 13,
    description: 'Attend a CEO job interview.',
    scenarioPrompt: 'You are being interviewed for a CEO position at a medium-sized Danish company.',
    npcName: 'Bestyrelsesmedlem', npcRole: 'bestyrelsesmedlem (board member)',
    requiredPhrases: ['Min ledelsesfilosofi er baseret på', 'Jeg har vendt en virksomhed rundt før', 'Min strategi for de næste tre år er'] },
  { title: 'Lægekonference', slug: 'medical-conference', category: 'health', level: 'C1', order: 14,
    description: 'Present research at a medical conference.',
    scenarioPrompt: 'You are a medical researcher presenting your findings at a conference.',
    npcName: 'Professor', npcRole: 'konferenceformand (conference chair)',
    requiredPhrases: ['Vores kliniske studie viser', 'Patientgruppen bestod af', 'Resultaterne er statistisk signifikante'] },
  { title: 'Forhandle huskøb', slug: 'house-purchase-negotiation', category: 'housing', level: 'C1', order: 15,
    description: 'Negotiate the price of a house.',
    scenarioPrompt: 'You found your dream home. Negotiate the price and terms with the seller.',
    npcName: 'Sælger', npcRole: 'boligsælger (home seller)',
    requiredPhrases: ['Jeg vil gerne give et bud', 'Prisen er lidt høj i forhold til markedet', 'Kan vi mødes på midten?'] },
  { title: 'Fagforeningsforhandling', slug: 'union-negotiation', category: 'work', level: 'C1', order: 16,
    description: 'Negotiate collective agreement terms.',
    scenarioPrompt: 'You are a union representative negotiating a new collective agreement with employers.',
    npcName: 'Arbejdsgiverrepræsentant', npcRole: 'arbejdsgiverkonsulent (employer consultant)',
    requiredPhrases: ['Vores medlemmer kræver', 'Vi foreslår en lønstigning på', 'Arbejdstiden bør reduceres'] },
  { title: 'Retssag som vidne', slug: 'court-witness', category: 'government', level: 'C1', order: 17,
    description: 'Testify as a witness in court.',
    scenarioPrompt: 'You witnessed a traffic accident. You are called to testify in court.',
    npcName: 'Dommeren', npcRole: 'dommer (judge)',
    requiredPhrases: ['Jeg så ulykken ske', 'Bilen kom fra venstre', 'Jeg er sikker på, hvad jeg så'] },
  { title: 'Til samtale om forskningsetisk komité', slug: 'ethics-committee', category: 'education', level: 'C1', order: 18,
    description: 'Present your research to the ethics committee.',
    scenarioPrompt: 'Your research involves human subjects. Present your ethical considerations to the committee.',
    npcName: 'Professor', npcRole: 'forskningsetisk komité (ethics committee)',
    requiredPhrases: ['Forsøgspersonerne er informeret', 'Alle data er anonymiserede', 'Samtykkeerklæringen er vedlagt'] },
  { title: 'Politisk debat', slug: 'political-debate', category: 'citizenship', level: 'C1', order: 19,
    description: 'Engage in a political discussion.',
    scenarioPrompt: 'You are at a political meeting discussing climate policy.',
    npcName: 'Politiker', npcRole: 'folketingsmedlem (MP)',
    requiredPhrases: ['Jeg mener, at klimapolitikken bør', 'Partiets forslag er utilstrækkeligt', 'Vi har brug for handling nu'] },
  { title: 'Møde med banken om formueforvaltning', slug: 'wealth-management', category: 'finance', level: 'C1', order: 20,
    description: 'Discuss wealth management with your private banker.',
    scenarioPrompt: 'You have significant assets and need a comprehensive wealth management strategy.',
    npcName: 'Privatbankrådgiver', npcRole: 'private banker (private banking advisor)',
    requiredPhrases: ['Jeg ønsker en diversificeret portefølje', 'Hvordan minimerer vi skatten?', 'Jeg tænker langsigtet'] },
  { title: 'Leder af en workshop', slug: 'lead-workshop', category: 'work', level: 'C1', order: 21,
    description: 'Lead a professional workshop for colleagues.',
    scenarioPrompt: 'You are leading a workshop on cross-cultural communication for your international team.',
    npcName: 'Deltager', npcRole: 'workshopdeltager (workshop participant)',
    requiredPhrases: ['Lad os starte med en øvelse', 'Kulturforskelle kan påvirke', 'Hvad er jeres erfaringer?'] },
  { title: 'Interview i avis', slug: 'newspaper-interview', category: 'social', level: 'C1', order: 22,
    description: 'Give an interview to a newspaper.',
    scenarioPrompt: 'A journalist wants to interview you about your work in the local community.',
    npcName: 'Journalist', npcRole: 'journalist (journalist)',
    requiredPhrases: ['Mit arbejde handler om', 'Jeg startede fordi', 'Fremtiden ser lys ud fordi'] },
  { title: 'Ansøgning om dansk pas', slug: 'danish-passport', category: 'citizenship', level: 'C1', order: 23,
    description: 'Apply for a Danish passport.',
    scenarioPrompt: 'You are now a Danish citizen and want to apply for your first Danish passport.',
    npcName: 'Borgerservice', npcRole: 'borgerservicemedarbejder (citizen service)',
    requiredPhrases: ['Jeg har fået dansk statsborgerskab', 'Jeg vil gerne ansøge om pas', 'Hvor lang tid tager det?'] },
  { title: 'Mægling i en konflikt', slug: 'mediation', category: 'work', level: 'C1', order: 24,
    description: 'Mediate a conflict between two colleagues.',
    scenarioPrompt: 'Two team members have a serious conflict. As their manager, you mediate.',
    npcName: 'Konfliktpart', npcRole: 'medarbejder (employee)',
    requiredPhrases: ['Jeg forstår jeres perspektiver', 'Lad os finde en fælles løsning', 'Hvad har I brug for?'] },
  { title: 'Indvielse af ny afdeling', slug: 'department-launch', category: 'work', level: 'C1', order: 25,
    description: 'Give a speech at the opening of a new department.',
    scenarioPrompt: 'Your company opens a new department. Give an inspiring opening speech.',
    npcName: 'Direktør', npcRole: 'administrerende direktør (CEO)',
    requiredPhrases: ['Det er en stor dag for os', 'Denne afdeling vil fokusere på', 'Jeg vil takke alle, der har gjort det muligt'] },
  { title: 'Tale til bryllup', slug: 'wedding-speech', category: 'social', level: 'C1', order: 26,
    description: 'Give a speech at a Danish wedding.',
    scenarioPrompt: 'Your best friend is getting married. You are the best man and need to give a speech.',
    npcName: 'Brudgom', npcRole: 'brudgom (groom)',
    requiredPhrases: ['Kære brudepar', 'Jeg har kendt dig i mange år', 'Skål for jer begge'] },
  { title: 'Kontraktforhandling med leverandør', slug: 'supplier-negotiation', category: 'work', level: 'C1', order: 27,
    description: 'Negotiate a contract with a supplier.',
    scenarioPrompt: 'You are negotiating a long-term supply agreement with a key vendor.',
    npcName: 'Sælger', npcRole: 'leverandør (supplier)',
    requiredPhrases: ['Vi har brug for bedre betalingsbetingelser', 'Kvaliteten skal være garanteret', 'Lad os lave en 2-årig aftale'] },
  { title: 'Lobbyarbejde', slug: 'lobbying', category: 'citizenship', level: 'C1', order: 28,
    description: 'Lobby politicians about an important issue.',
    scenarioPrompt: 'You represent an NGO lobbying for better environmental policies.',
    npcName: 'Politiker', npcRole: 'miljøordfører (environment spokesperson)',
    requiredPhrases: ['Vores organisation foreslår', 'Miljøpåvirkningen kan reduceres ved', 'Vi opfordrer til strengere regulering'] },
  { title: 'Foredrag på universitetet', slug: 'university-lecture', category: 'education', level: 'C1', order: 29,
    description: 'Give a guest lecture at the university.',
    scenarioPrompt: 'You are invited as a guest lecturer to speak about your field of expertise.',
    npcName: 'Professor', npcRole: 'institutleder (department head)',
    requiredPhrases: ['I dag vil jeg tale om', 'Forskningen viser at', 'Hvad er jeres spørgsmål?'] },
  { title: 'Ansættelse af ny medarbejder', slug: 'hiring-interview', category: 'work', level: 'C1', order: 30,
    description: 'Interview and hire a new employee.',
    scenarioPrompt: 'You are hiring for your team. Interview a promising candidate.',
    npcName: 'Kandidat', npcRole: 'jobkandidat (job candidate)',
    requiredPhrases: ['Hvad er dine styrker?', 'Hvordan håndterer du pres?', 'Hvor ser du dig selv om 5 år?'] },
  { title: 'Sikkerhedsgodkendelse', slug: 'security-clearance', category: 'work', level: 'C1', order: 31,
    description: 'Apply for a security clearance.',
    scenarioPrompt: 'Your new job requires a security clearance. Attend an interview about your background.',
    npcName: 'PET-medarbejder', npcRole: 'sikkerhedsgodkendelsesmedarbejder (security officer)',
    requiredPhrases: ['Jeg forstår fortrolighedskravene', 'Min baggrund er', 'Jeg har ikke noget at skjule'] },
  { title: 'Vurdering af advokat', slug: 'lawyer-consultation', category: 'citizenship', level: 'C1', order: 32,
    description: 'Meet a lawyer about starting a business.',
    scenarioPrompt: 'You want to start a company. Meet a business lawyer to discuss legal structure.',
    npcName: 'Advokat', npcRole: 'erhvervsadvokat (business lawyer)',
    requiredPhrases: ['Jeg overvejer at starte en virksomhed', 'Hvad er den bedste selskabsform?', 'Hvad skal jeg være opmærksom på?'] },
  { title: 'Strategisk planlægningsmøde', slug: 'strategic-planning', category: 'work', level: 'C1', order: 33,
    description: 'Lead a strategic planning session.',
    scenarioPrompt: 'You are facilitating the annual strategic planning session for your department.',
    npcName: 'Kollegia', npcRole: 'teamleder (team leader)',
    requiredPhrases: ['Vores vision for næste år er', 'Hvad er vores vigtigste mål?', 'Vi skal prioritere ressourcerne'] },
  { title: 'Pressekonference', slug: 'press-conference', category: 'work', level: 'C1', order: 34,
    description: 'Speak at a press conference.',
    scenarioPrompt: 'Your company is launching a major new product. Answer questions from journalists.',
    npcName: 'Journalist', npcRole: 'journalist (journalist)',
    requiredPhrases: ['Vi er stolte af at præsentere', 'Produktet er resultatet af', 'Vi forventer en omsætning på'] },
  { title: 'Evaluering af medarbejder', slug: 'employee-review', category: 'work', level: 'C1', order: 35,
    description: 'Conduct a performance review with an employee.',
    scenarioPrompt: 'It is time for the annual performance review with one of your team members.',
    npcName: 'Medarbejder', npcRole: 'medarbejder (employee)',
    requiredPhrases: ['Du har gjort et godt stykke arbejde', 'Der er områder du kan forbedre', 'Lad os sætte mål for næste år'] },
  { title: 'Til optagelsessamtale', slug: 'university-admission', category: 'education', level: 'C1', order: 36,
    description: 'Attend a university admission interview.',
    scenarioPrompt: 'You are applying for a masters programme. The admission committee interviews you.',
    npcName: 'Professor', npcRole: 'optagelsesudvalg (admission committee)',
    requiredPhrases: ['Jeg er motiveret fordi', 'Min bachelor er i', 'Jeg håber at specialisere mig i'] },
  { title: 'Bestyrelsesmøde', slug: 'board-meeting', category: 'work', level: 'C1', order: 37,
    description: 'Present at a board meeting.',
    scenarioPrompt: 'You are invited to present a proposal to the board of directors.',
    npcName: 'Bestyrelse', npcRole: 'bestyrelsesmedlem (board member)',
    requiredPhrases: ['Jeg foreslår en investering på', 'Afkastet forventes at være', 'Risikovurderingen viser'] },
  { title: 'Søge om statsborgerskab', slug: 'citizenship-application', category: 'citizenship', level: 'C1', order: 38,
    description: 'Submit your Danish citizenship application.',
    scenarioPrompt: 'You meet the requirements for Danish citizenship. Submit your application.',
    npcName: 'Sagsbehandler', npcRole: 'statsborgerskabskontoret (citizenship office)',
    requiredPhrases: ['Jeg opfylder betingelserne', 'Jeg har bestået sprogprøven', 'Jeg har boet her i over 9 år'] },
  { title: 'Til læge med kompleks diagnose', slug: 'complex-diagnosis', category: 'health', level: 'C1', order: 39,
    description: 'Discuss a complex medical diagnosis with a specialist.',
    scenarioPrompt: 'You have a rare condition. Discuss treatment options with a specialist at the hospital.',
    npcName: 'Overlæge', npcRole: 'overlæge (senior consultant)',
    requiredPhrases: ['Jeg har fået diagnosen', 'Hvad er behandlingsmulighederne?', 'Hvad er prognosen på lang sigt?'] },
  { title: 'Fusion af virksomheder', slug: 'company-merger', category: 'work', level: 'C1', order: 40,
    description: 'Discuss a company merger.',
    scenarioPrompt: 'Your company is considering merging with another. Discuss the implications with the board.',
    npcName: 'Advokat', npcRole: 'fusionsekspert (merger expert)',
    requiredPhrases: ['Fusionen vil skabe synergier', 'Der er regulatoriske udfordringer', 'Due diligence processen kræver'] },
  { title: 'Interview til kandidatprogram', slug: 'graduate-program', category: 'education', level: 'C1', order: 41,
    description: 'Apply for a competitive graduate program.',
    scenarioPrompt: 'You are interviewing for a prestigious graduate program at a large Danish company.',
    npcName: 'HR', npcRole: 'talent acquisition manager',
    requiredPhrases: ['Jeg har ledelsespotentiale', 'Jeg har erfaring fra', 'Min motivation for programmet er'] },
  { title: 'Krisehåndteringsmøde', slug: 'crisis-management', category: 'work', level: 'C1', order: 42,
    description: 'Handle a PR crisis.',
    scenarioPrompt: 'Your company faces a PR crisis. Lead the crisis management team meeting.',
    npcName: 'PR-rådgiver', npcRole: 'PR-rådgiver (PR advisor)',
    requiredPhrases: ['Vi skal håndtere denne situation', 'Pressen har fået historien', 'Vores udtalelse bør være'] },
  { title: 'Forhandle lønforhøjelse', slug: 'salary-increase', category: 'work', level: 'C1', order: 43,
    description: 'Negotiate a salary increase with your boss.',
    scenarioPrompt: 'You believe you deserve a raise. Present your case to your manager.',
    npcName: 'Chef', npcRole: 'chef (manager)',
    requiredPhrases: ['Jeg har opnået betydelige resultater', 'Mit ansvar er vokset', 'Jeg foreslår en lønstigning på'] },
  { title: 'Møde med revisor', slug: 'accountant-meeting', category: 'finance', level: 'C1', order: 44,
    description: 'Year-end meeting with your accountant.',
    scenarioPrompt: 'It is year-end. Meet with your accountant to review the annual accounts.',
    npcName: 'Revisor', npcRole: 'statsautoriseret revisor (authorized accountant)',
    requiredPhrases: ['Årsregnskabet viser', 'Der er skattemæssige overvejelser', 'Vi kan optimere ved'] },
  { title: 'Til eksamen mundtlig', slug: 'oral-exam', category: 'education', level: 'C1', order: 45,
    description: 'Take an oral exam at university.',
    scenarioPrompt: 'Your final oral exam. The examiner questions you on the curriculum.',
    npcName: 'Eksaminator', npcRole: 'universitetslektor (associate professor)',
    requiredPhrases: ['Jeg vil gerne starte med at sige', 'Teorien om', 'I forhold til pensum vil jeg fremhæve'] },
  { title: 'Patentansøgning', slug: 'patent-application', category: 'work', level: 'C1', order: 46,
    description: 'File a patent application.',
    scenarioPrompt: 'You invented something new. Meet with a patent attorney to file a patent.',
    npcName: 'Patentadvokat', npcRole: 'patentrådgiver (patent attorney)',
    requiredPhrases: ['Min opfindelse løser problemet med', 'Patentkravene bør dække', 'Jeg har dokumentation for'] },
  { title: 'Ambassademøde', slug: 'embassy-meeting', category: 'citizenship', level: 'C1', order: 47,
    description: 'Attend a meeting at your embassy.',
    scenarioPrompt: 'You need assistance with a consular matter. Meet with a consular officer.',
    npcName: 'Konsul', npcRole: 'konsul (consul)',
    requiredPhrases: ['Jeg har brug for konsulær bistand', 'Mit pas er udløbet', 'Kan I hjælpe med'] },
  { title: 'Foredrag på konference', slug: 'conference-keynote', category: 'work', level: 'C1', order: 48,
    description: 'Deliver a keynote speech at a conference.',
    scenarioPrompt: 'You are the keynote speaker at an international conference in Copenhagen.',
    npcName: 'Konferenceleder', npcRole: 'konferencearrangør (conference organizer)',
    requiredPhrases: ['Det er en ære at tale her i dag', 'Lad mig starte med et spørgsmål', 'Min centrale pointe er'] },
  { title: 'Indvielse af byggeri', slug: 'construction-inauguration', category: 'government', level: 'C1', order: 49,
    description: 'Speak at the inauguration of a new building.',
    scenarioPrompt: 'A new community centre is opening. As a local representative, give a speech.',
    npcName: 'Borgmester', npcRole: 'borgmester (mayor)',
    requiredPhrases: ['Dette byggeri har været længe ventet', 'Det vil gavne lokalsamfundet', 'Jeg vil gerne takke alle involverede'] },
  { title: 'Debatarrangement om integration', slug: 'integration-debate', category: 'citizenship', level: 'C1', order: 50,
    description: 'Participate in a panel debate about integration.',
    scenarioPrompt: 'You are on a panel discussing integration of immigrants in Danish society.',
    npcName: 'Ordstyrer', npcRole: 'debatleder (moderator)',
    requiredPhrases: ['Min erfaring som indvandrer er', 'Integration er en to-vejs proces', 'Vi har alle et ansvar for'] },
];

async function seed(): Promise<void> {
  try {
    await mongoose.connect(`${env.MONGO_URI}/${env.DB_NAME}`);
    console.log('Connected to MongoDB');

    await Mission.deleteMany({});
    console.log('Cleared existing missions');

    const BATCH_SIZE = 50;
    for (let i = 0; i < missions.length; i += BATCH_SIZE) {
      const batch = missions.slice(i, i + BATCH_SIZE);
      await Mission.insertMany(batch);
      console.log(`  Inserted ${Math.min(i + BATCH_SIZE, missions.length)}/${missions.length} missions`);
    }
    console.log(`\nSeeded ${missions.length} missions:\n`);

    const levels = ['A1', 'A2', 'B1', 'B2', 'C1'] as const;
    for (const level of levels) {
      const count = missions.filter((m: any) => m.level === level).length;
      if (count > 0) console.log(`  DA ${level}: ${count} missions`);
    }

    console.log('\nDone!');
    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();
